config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'menus#index'
  resources :menus do
    collection do
      get 'search'
      get 'following_menus'
    end
    resource :favorites, only: [:create, :destroy]
  end 
  resources :users, only: :show do
    member do
      get 'favorite_menus'
      get :follows, :followers
      get 'mypage'
    end
    collection do
      get 'search'
      get 'user_search'  
    end
    resource :relationships, only: [:create, :destroy]
  end
  resources :welcome, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :menu
end

app/models/menu.rb
class Menu < ApplicationRecord
  validates :name, presence: true
  validates :url, presence: true
  belongs_to :user
  has_one_attached :image
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :menus
  has_many :favorites, dependent: :destroy
  has_many :favorite_menus, through: :favorites, source: :menu
  has_many :follower, class_name: "Relationship",foreign_key: "follower_id",dependent: :destroy
  has_many :followed, class_name: "Relationship",foreign_key: "followed_id",dependent: :destroy
  has_many :following_users, through: :follower, source: :followed 
  has_many :follower_users, through: :followed, source: :follower 
  
  validates :nickname, presence: true, length: { maximum: 6 }

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_users.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected
  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to welcome_index_path
    end
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_menu
  
  def create
    if user_signed_in?
      favorite = current_user.favorites.build(menu_id: params[:menu_id])
      favorite.save
      render 'create.js.erb'
    end
  end

  def destroy
    favorite = Favorite.find_by(menu_id: params[:menu_id], user_id: current_user.id)
    favorite.destroy
    render 'destroy.js.erb'
  end

  def set_menu
    @menu = Menu.find(params[:menu_id])
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :move_to_index, except: [:index, :show, :search]
  
  def index
    @page = "menus"
    @menus = current_user.menus.order("created_at DESC")
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
      if @menu.save
        redirect_to root_path
      else
        render :new
      end
  end

  def destroy
    menu = Menu.find(params[:id])
    menu.destroy
    redirect_to root_path
  end

  def edit
    @menu = Menu.find(params[:id])
    
  end

  def update
    menu = Menu.find(params[:id])
    menu.update(menu_params)
    redirect_to root_path
  end

  def show
    @menu = Menu.find(params[:id])
  end

  def search
    @menus = Menu.all
    if params[:word].present?
      @menus = Menu.where('name LIKE ?', "%#{params[:word]}%")
    end
  end

  def favorite
    @menu = Menu.find(params[:id])
    Favorite.create(user_id: current_user.id, menu_id: @menu.id)
    render :show
  end


  def following_menus
    @page = "followings"
    if user_signed_in?
     following_user_id = current_user.following_users.pluck(:id)
    end
    @menus = Menu.where(user_id: following_user_id).order("created_at DESC")
  end  

  private
  def menu_params
    if params.require(:menu).permit(:image)[:image]
      image_size =  ImageProcessing::MiniMagick.source(params.require(:menu).permit(:image)[:image].tempfile).call.size
      # 画像が500kB以上ならリサイズする
      if image_size > 500000
        resized_image = ImageProcessing::MiniMagick.source(params.require(:menu).permit(:image)[:image].tempfile).resize_to_fit(500,500).call
        new_params = params
        new_params.require(:menu).permit(:image)[:image].tempfile = resized_image
        new_params.require(:menu).permit(:name, :url, :memo, :image).merge(user_id: current_user.id)
      else
        params.require(:menu).permit(:name, :url, :memo, :image).merge(user_id: current_user.id)
      end
    else
      params.require(:menu).permit(:name, :url, :memo, :image).merge(user_id: current_user.id)
    end
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def follows
    user = User.find(params[:id])
    @users = user.following_users.page(params[:page]).per(3).reverse_order
  end
  
  def followers
    user = User.find(params[:id])
    @users = user.follower_users.page(params[:page]).per(3).reverse_order
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
    
  def show
    @user = User.find(params[:id])
    @nickname = @user.nickname
    @menus = @user.menus
  end

  
  def mypage
    @nickname = current_user.nickname
    @menus = current_user.menus
    @user = User.find(params[:id])
    @following_users = @user.following_users
    @follower_users = @user.follower_users
  end

  def favorite_menus
    @page = "likes"
    @menus = current_user.favorite_menus.order("created_at DESC")
  end

  def user_search
  end
  
  def search
    if params[:keyword].present?
      @users = User.where('nickname LIKE ?', "%#{params[:keyword]}%")
      @users = nil if @users.empty?
    else
      @users = []
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: 'Recipist',
      title: '育てよう。あなただけのレシピライブラリ',
      reverse: true,
      charset: 'utf-8',
      description: '日々の料理レシピを、レシピサイトのURLと一緒に記録し、シェアできます。',
      keywords: '料理,レシピ,ご飯',
      canonical: request.original_url,
      separator: '|',
      og: {
        site_name: :site,
        title: :title,
        description: :description,
        type: 'website',
        url: request.original_url,
        image: nil,
        local: 'ja-JP',
      },
      twitter: {
        card: 'summary_large_image',
        image: 'https://odendayoko0001.s3.ap-northeast-1.amazonaws.com/introduction.jpg',
      }
    }
  end
end

    

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
  <% if menu.favorited_by?(current_user) %>
    <%=link_to menu_favorites_path(menu.id), method: :delete ,remote: true do %>
      <i class="fa-solid fa-star unlike-btn"></i>
    <% end %>
  <% else %>
     <%=link_to menu_favorites_path(menu.id), method: :post,remote: true do %>
      <i class="fa-solid fa-star like-btn"></i>
     <% end %>
  <% end %>
<% else %>
  <div id="favorite-button<%= menu.id %>">
    <%=link_to menu_favorites_path(menu.id), method: :post do %>
      <i class="fa-solid fa-star like-btn"></i>
    <% end %>
  </div>
<% end %>

app/views/favorites/create.js.erb
document.getElementById('favorite-button<%= @menu.id %>').innerHTML = "<%= j(render partial: 'favorites/favorite', locals: {menu: @menu}) %>"

app/views/favorites/destroy.js.erb
document.getElementById('favorite-button<%= @menu.id %>').innerHTML = "<%= j(render partial: 'favorites/favorite', locals: {menu: @menu}) %>"

app/views/layouts/_pagelink.html.erb
<% if user_signed_in? %>
  <div class="search-top">
    <%= form_with(url: search_menus_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :word, placeholder: "レシピ名", class: "search-input" %>
      <%= form.submit "検索", class: "search-button" %>
    <% end %>
  </div>
<% end %>

<%=link_to new_menu_path, method: :get,class:"new-recipe-button" do%>
  <i class="fa-solid fa-utensils"></i>
<% end %>

<% if @page == "menus" %>
  <div class="top-link">
    <div class="links">
    <%= link_to "Recipies", root_path,class: "link", style: "color: #bc611e; border-bottom: 3px solid #bc611e" %>
    <%= link_to "Likes", "/users/#{current_user.id}/favorite_menus",class: "link"%>
    <%= link_to "Follwing", "/menus/following_menus",class: "link"%>
    </div>
  </div>

<% elsif @page == "likes" %>
  <div class="top-link">
    <div class="links">
    <%= link_to "Recipies", root_path,class: "link" %>
    <%= link_to "Likes", "/users/#{current_user.id}/favorite_menus",class: "link", style: "color: #bc611e; border-bottom: 3px solid #bc611e"%>
    <%= link_to "Follwing", "/menus/following_menus",class: "link"%>
    </div>
  </div>

<% elsif @page == "followings" %>
  <div class="top-link">
    <div class="links">
    <%= link_to "Recipies", root_path,class: "link" %>
    <%= link_to "Likes", "/users/#{current_user.id}/favorite_menus",class: "link"%>
    <%= link_to "Follwing", "/menus/following_menus",class: "link", style: "color: #bc611e; border-bottom: 3px solid #bc611e"%>
    </div>
  </div>
<% end %>


      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <link rel="stylesheet" href='https://use.fontawesome.com/releases/v6.4.0/css/all.css'>
    <%= display_meta_tags(default_meta_tags) %>
  </head>

  <body>
     <header class="header">
     <div class="header-top">
        <div class="header-bar">
          <h1 class="header-logo"><a href="/">Recipist</a></h1>
          <% if user_signed_in? %>
            <div class="hamburger">
              <span></span>
              <span></span>
              <span></span>
            </div>
            <div class="hamburger-menu">       
              <div class = "user-name">
                <%= current_user.nickname %>
              </div>
              <%= link_to "マイページ", "/users/#{current_user.id}/mypage",class: "post"%>
              <%= link_to "ユーザー検索", "/users/user_search",class: "post"%>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: "post"%>
            </div>
          <% else %>
            <div class ="header-menu">
              <%= link_to "ログイン", new_user_session_path, class: "header-login-button" %>
            </div>
          <% end %>
        </div>
      </div>
      
    </header>
    <%= yield %>
    <footer>
      <div class="container">
      <div class="logout">
        <%= "Copyright Recipist 2023." %>
   
      </div>  
    </footer>
  </body>
</html>

app/views/menus/edit.html.erb
<div class="contents">
  <div class="container">

  <%= button_to menu_path(@menu.id), method: :delete, data: {confirm: "レシピを削除しますか？"},class: "delete-button" do%>
    <i class="fa-regular fa-trash-can"></i>
  <% end %>
    <h2>レシピを編集する</h2>

    <% if @menu.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @menu.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <%= form_with(model: @menu, local: true,class: "new-main") do |form| %>
    <div class = "new-recipe-name">
     <div class = "new-title"> <%= "料理名" %> </div>
      <%= form.text_field :name, placeholder: "料理名を入力",class: "new-recipe-form" %>
    </div>
    <div class = "new-recipe-url">
     <div class = "new-title"> <%= "URL" %> </div>
      <%= form.text_field :url, placeholder: "URLを入力",class: "new-recipe-form"%>
    </div>
    <div class = "new-recipe-memo">
     <div class = "new-title"> <%= "メモ" %> </div>
      <%= form.text_area :memo, placeholder: "メモを入力",class: "new-recipe-form memo-field"%>
    </div>
    <div class = "new-recipe-image">
     <div class = "new-title"> <%= "写真" %> </div>
      <%= form.file_field :image ,class:"new-recipe-form" %>
    </div>
    <div class = "new-submit">
      <%= form.submit "保存" ,class: "new-submit-button"%>
    </div>
    <% end %>


  </div>
</div>

app/views/menus/following_menus.html.erb
<div class="body-container">
  <%= render 'layouts/pagelink'%>

  <div class="container">
    <div class="recipe-list">
      <% @menus.each do |menu| %>
        <div class="index-recipe">
          <div class="index-recipe-image">
            <%= link_to menu_path(menu.id) do %>
              <%= image_tag menu.image if menu.image.attached? %>
            <% end %>
          </div>
          <div class="index-recipe-name">
            <%= link_to "#{menu.name}" , menu_path(menu.id)%>
          </div>
          <div class= "favorite-recipe-user">
            <%= "by #{menu.user.nickname}" %>
          </div>
          <div class="index-recipe-link">
            <%= link_to menu.url, target: "_blank" do %>
              <i class="fa-solid fa-up-right-from-square"></i>  レシピを見る
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/menus/index.html.erb
<div class= "body-container">
  <%= render 'layouts/pagelink'%>

  <div class ="container">
    <div class="recipe-list">
      <% @menus.each do |menu| %>
        <div class="index-recipe">
          <div class="index-recipe-image">
            <%= link_to menu_path(menu.id) do %>
              <%= image_tag menu.image if menu.image.attached? %>
            <% end %>
          </div>
          <div class="index-recipe-name">
            <%= link_to "#{menu.name}" , menu_path(menu.id)%>
          </div>
          <div class="index-recipe-link">
            <%= link_to menu.url, target: "_blank" do %>
              <i class="fa-solid fa-up-right-from-square"></i>  レシピを見る
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/menus/new.html.erb
<div class="contents">
  <div class="container">
    <h2>レシピを追加する</h2>

    <% if @menu.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @menu.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <%= form_with(model: @menu, local: true,class: "new-main") do |form| %>
    <div class = "new-recipe-name">
     <div class = "new-title"> <%= "料理名" %> </div>
      <%= form.text_field :name, placeholder: "料理名を入力",class: "new-recipe-form" %>
    </div>
    <div class = "new-recipe-url">
     <div class = "new-title"> <%= "URL" %> </div>
      <%= form.text_field :url, placeholder: "URLを入力",class: "new-recipe-form"%>
    </div>
    <div class = "new-recipe-memo">
     <div class = "new-title"> <%= "メモ" %> </div>
      <%= form.text_area :memo, placeholder: "メモを入力",class: "new-recipe-form memo-field"%>
    </div>
    <div class = "new-recipe-image">
     <div class = "new-title"> <%= "写真" %> </div>
      <%= form.file_field :image ,class:"new-recipe-form" %>
    </div>
    <div class = new-submit>
      <%= form.submit "保存" ,class: "new-submit-button"%>
    </div>
    <% end %>
  </div>
</div>

app/views/menus/search.html.erb
<div class = "container">
  <div class="recipe-list">
    <% @menus.each do |menu| %>
      <div class="index-recipe">
        <div class="index-recipe-image">
          <%= link_to menu_path(menu.id) do %>
            <%= image_tag menu.image if menu.image.attached? %>
      <% end %>
      </div>
       <div class="index-recipe-name">
          <%= link_to "#{menu.name}" , menu_path(menu.id)%>
        </div>
        <div class="index-recipe-url">
          <%= link_to "#{menu.url}", menu.url, target: "_blank"%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/menus/show.html.erb
<% if @menu.image.attached? %>
  <% set_meta_tags title: @menu.name, description: @menu.memo,twitter:{image: image_url(@menu.image.attachment.service.send(:object_for,@menu.image.key).public_url)} %>
<% end %>

<div class="container">
  <div class = "show-hed">
    <% if user_signed_in? %>
      <div class = "show-back-button" >
        <%= link_to request.referrer, method: :get do%>
          <i class="fa-solid fa-chevron-left"></i>
        <% end %>
      </div>
    <% end %>
    <% if user_signed_in? && @menu.user.id == current_user.id %>
        <div class= "show-edit-button">
          <%= link_to '編集', edit_menu_path(@menu.id), method: :get %>
        </div>
    <% end %>
  </div>


<div class="show-recipe-main-container">
  <div class="show-recipe-name">
    <%= @menu.name %>
  </div>

  <div class= "show-bar">
    <div class= "like-container">
      <div id="favorite-button<%= @menu.id %>">
        <%= render partial: "favorites/favorite", locals: {menu: @menu}%>
      </div>
    </div>
    
    <div class="share-container">
      <%= link_to "https://twitter.com/share?url=#{request.url}/&text=#{@menu.name}のレシピ", title: 'Twitter', target: '_blank' do %>
        <i class="fa-brands fa-twitter" style='color: #3399FF;'></i>
      <% end %>
      <%= link_to "https://social-plugins.line.me/lineit/share?url=#{request.url}/&text=#{@menu.name}のレシピ" do %>
        <i class="fa-brands fa-line" style='color: #06c755;'></i>
      <% end%>
    </div>
  </div>
  
  <div class="show-recipe-image">
    <%= image_tag @menu.image if @menu.image.attached? %>
  </div>
  
  <div class="show-recipe-contents">
    <div class = "show-recipe-link">
      <%= link_to @menu.url, target: "_blank",class: 'show-recipe-link-button' do %>
        <div class="link-icon">
          <i class="fa-solid fa-up-right-from-square"></i>レシピを見る
        </div>
      <% end %>
    </div>

    <div class = "show-recipe-list">
      <h3><%="メモ"%></h3>
      <div class='show-recipe-memo'>
        <%= @menu.memo %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/users/favorite_menus.html.erb
<div class="body-container">
  <%= render 'layouts/pagelink'%>

  <div class="container">
    <div class="recipe-list">
      <% @menus.each do |menu| %>
        <div class="index-recipe">
          <div class="index-recipe-image">
            <%= link_to menu_path(menu.id) do %>
              <%= image_tag menu.image if menu.image.attached? %>
            <% end %>
          </div>
          <div class="index-recipe-name">
            <%= link_to "#{menu.name}" , menu_path(menu.id)%>
          </div>
          <div class= "favorite-recipe-user">
            <%= "by #{menu.user.nickname}" %>
          </div>
          <div class="index-recipe-link">
            <%= link_to menu.url, target: "_blank" do %>
              <i class="fa-solid fa-up-right-from-square"></i>  レシピを見る
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/mypage.html.erb
<div class="container">
  <h2><%= @nickname %></h2>
  <div class="follow-content">
    <div class="following">
      <%= "Following" %>
      <%= @following_users.count %>
    </div>
    <div class="followers">
      <%= "Followers" %>
      <%=  @follower_users.count %>
    </div>
  </div>
</div>

app/views/users/search.html.erb
<div class="container">
  <%= form_with(url: search_users_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "ユーザーを検索", class: "search-input" %>
    <%= form.submit "検索", class: "search-button" %>
  <% end %>

  <div class="user-search-contents">
    <% if @users %>
      <% @users.each do |user| %>
          <div class="user-search-content">
            <%= link_to "#{user.nickname}", "/users/#{user.id}",class: 'user-search-name'%>
            <% if current_user != user %>
              <% if current_user.following?(user) %>
                <%= link_to 'フォロー中', user_relationships_path(user.id), method: :delete, class: "unfollow-button" %>
              <% else %>
              <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST, class:"follow-button" %>
              <% end %>
            <% end %>
          </div>
      <% end %>
    <% else %>
      <p class="user-search-text">ユーザーが見つかりませんでした</p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="user-show-head">
    <h1 class= "user-show-name"><%= @nickname %></h1>
    <% if current_user != @user %>
      <% if current_user.following?(@user) %>
        <%= link_to 'フォロー中', user_relationships_path(@user.id), method: :delete, class: "unfollow-button" %>
      <% else %>
      <%= link_to 'フォローする', user_relationships_path(@user.id), method: :POST, class:"follow-button" %>
      <% end %>
    <% end %>
  </div>

  <div class="recipe-list">
    <% @menus.each do |menu| %>
      <div class="index-recipe">
        <div class="index-recipe-image">
          <%= link_to menu_path(menu.id) do %>
            <%= image_tag menu.image if menu.image.attached? %>
          <% end %>
        </div>
        <div class="index-recipe-name">
          <%= link_to "#{menu.name}" , menu_path(menu.id)%>
        </div>
        <div class="index-recipe-url">
          <%= link_to "レシピのURL: #{menu.url}", menu.url, target: "_blank"%>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/users/user_search.html.erb
<div class="container">
  <%= form_with(url: search_users_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "ユーザーを検索", class: "search-input" %>
    <%= form.submit "検索", class: "search-button" %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <div class="welcome-top">
    <div class="welcome-top-content">
      <p>育てよう。<br>あなただけのレシピライブラリ</p>
      <h1>「Recipist」</h1>
    </div>
    <img src="https://odendayoko0001.s3.ap-northeast-1.amazonaws.com/welcome-top.jpg" class="welcome-top-img">
  </div>

  <div class="welcome-main-contents">
    <h2 class = "welcome-title"><span>レシピの迷子にさよなら</span></h2>
    <p class = "welcome-intro">Recipistは作った料理のレシピを管理・整理するためのアプリケーションです。</p>
    <p class = "welcome-intro">あなただけのレシピライブラリを育てましょう。</p>
    <%= button_to "会員登録はこちら","users/sign_up", method: :get, class: "welcome-registration-button" %>  
  </div>
  <div class = "welcome-main-contents" >
    <h2 class = "welcome-title"><span>こんなお悩みありませんか？</span></h2>
      <div class ="welcome-main-content">
        <h4 class="welcome-main-index">レシピを見失う</h4>
        <p>レシピ投稿サイトやSNS、動画サイトなど、様々なサイトでレシピが公開されていて、作りたいと思ったときに、どこのサイトに掲載されていたかわからない。</p>
      </div>
      <div class ="welcome-main-content">
        <h4 class="welcome-main-index">美味しかったレシピを共有したい</h4>
        <p>家族や友人、恋人に美味しかったレシピを共有する手段が少ない。共有されても、そのレシピを保存できない。</p>
      </div>
      <div class="welcome-main-content">
        <div class="welcome-main-item">
          <img src="https://odendayoko0001.s3.ap-northeast-1.amazonaws.com/16600_color.png" class="welcome-main-item-image">
        </div> 
      </div>
  </div>

  <div class ="welcome-main-contents">
    <h2 class = "welcome-title"><span>Recipistでできること</span></h2>
    <div class="welcome-main-content">
        <h4 class ="welcome-main-index">作ったレシピを投稿！</h4>
        <p> 料理の写真や、レシピサイトのURLを一緒に保存できる！ </p>
      <div class="welcome-main-item">
        <img src="https://odendayoko0001.s3.ap-northeast-1.amazonaws.com/16515_color.png" class="welcome-main-item-image">
      </div>
    </div>
    <div class="welcome-main-content">
      <h4 class="welcome-main-index">他のユーザーをフォロー！</h4>
      <p>友人や家族が作ったレシピも見られる！</p>
      <div class="welcome-main-item">
        <img src="https://odendayoko0001.s3.ap-northeast-1.amazonaws.com/13122_color.png" class="welcome-main-item-image">
      </div>
    </div>
    <div class="welcome-main-content">
      <h4 class="welcome-main-index">レシピをお気に入り登録！</h4>
      <p>自分のレシピや、他のユーザーが作ったレシピもお気に入り一覧で見られる！</p>
      <div class="welcome-main-item">
        <img src="https://odendayoko0001.s3.ap-northeast-1.amazonaws.com/16780_color.png" class="welcome-main-item-image">
      </div>       
    </div>
    <div class="welcome-main-content">
      <h4 class="welcome-main-index">作ったレシピをSNSでシェア！</h4>
      <p>おすすめしたいレシピがあったらSNSでシェアしよう!</p>
      <div class="welcome-main-item">
        <img src="https://odendayoko0001.s3.ap-northeast-1.amazonaws.com/7077_color.png" class="welcome-main-item-image">
      </div>  
    </div>
  </div>
  <%= button_to "会員登録はこちら","users/sign_up", method: :get, class: "welcome-registration-button" %>  
</div>